Repository tailwarden/komiser, pull requests merged in 2023-07, with the labels that each got.

#876 fix(inputs): added maxlength for inputs
  dashboard/components/input/Input.tsx
  dashboard/components/inventory/components/InventoryLayout.tsx
  dashboard/components/inventory/components/InventorySearchBar.tsx
  dashboard/components/inventory/components/InventoryTagWrapper.tsx
  dashboard/components/inventory/components/filter/InventoryFilterOperator.tsx
  dashboard/components/inventory/components/filter/InventoryFilterValue.tsx
  dashboard/components/inventory/components/view/InventoryView.tsx
  dashboard/components/inventory/components/view/alerts/InventoryViewAlertsEditAlert.tsx
  dashboard/components/select-checkbox/SelectCheckbox.tsx
Labels: ui

#879 Tooltip UI implementation
  dashboard/components/dashboard/components/cloud-map/DashboardCloudMapTooltip.tsx
Labels: ui

#860 Fix issue(#823) mysql-instance
  models/resource.go
  providers/linode/compute/instances.go
  providers/linode/linode.go
  providers/linode/sql/mysql.go
Labels: linode

#885 Optimise CI: Cache Go Builds
  .github/workflows/build_test_pr.yml
Labels: cli

#887 Support Linode Postgres Instances
  providers/linode/linode.go
  providers/linode/postgres/instances.go
Labels: linode

#868 Added ECS Task Definition
  providers/aws/aws.go
  providers/aws/ec2/instances.go
  providers/aws/ecs/taskDefinitions.go
Labels: aws

#883 Dependency graph another attempt
  dashboard/components/explorer/dependency-graph/dependencygraph.tsx
  dashboard/components/explorer/dependency-graph/dependencygrapherror.tsx
  dashboard/components/explorer/dependency-graph/dependencygraphskeleton.tsx
  dashboard/components/explorer/dependency-graph/dependencygraphwrapper.tsx
  dashboard/components/explorer/dependency-graph/dependencygrapview.tsx
  dashboard/components/explorer/dependency-graph/hooks/useDependencyGraph.tsx
  dashboard/components/explorer/dependency-graph/nodes/nodes.tsx
  dashboard/components/navbar/Navbar.tsx
  dashboard/package-lock.json
  dashboard/package.json
  dashboard/pages/dashboard.tsx
  dashboard/pages/explorer.tsx
  dashboard/services/settingsService.ts
  handlers/resources_handler.go
  handlers/views_handler.go
  internal/api/v1/endpoints.go
  internal/internal.go
  migrations/20230619100000_add_new_relation_field.go
  models/relation.go
  models/resource.go
  package-lock.json
  package.json
  providers/aws/aws.go
  providers/aws/ec2/elastic_ips.go
  providers/aws/ec2/instances.go
  providers/aws/ec2/keypair.go
  providers/aws/ec2/security_groups.go
  providers/aws/ec2/volumes.go
  providers/aws/ec2/vpcs.go
Labels: ui, security

#899 fix(save-button): fixed save button layout
  dashboard/components/inventory/components/InventoryActiveFilters.tsx
  dashboard/components/inventory/components/view/InventoryView.tsx
  dashboard/components/inventory/components/view/InventoryViewHeader.tsx
  dashboard/pages/inventory.tsx
Labels: ui

#886 feat: collect aws rds auto backup resources
  providers/aws/aws.go
  providers/aws/rds/auto_backups.go
Labels: aws

#902 fix(filter-button): repositioned filter button
  dashboard/components/icons/ClearFilterIcon.tsx
  dashboard/components/inventory/components/InventoryActiveFilters.tsx
  dashboard/components/inventory/components/InventoryHeader.tsx
  dashboard/components/inventory/components/filter/InventoryFilter.tsx
  dashboard/pages/inventory.tsx
Labels: ui

#880 Feature/786 onboarding wizard
  dashboard/components/icons/DocumentTextIcon.tsx
  dashboard/components/icons/Folder2Icon.tsx
  dashboard/components/icons/KeyIcon.tsx
  dashboard/components/icons/RecordCircleIcon.tsx
  dashboard/components/icons/ShieldSecurityIcon.tsx
  dashboard/components/icons/VariableIcon.tsx
  dashboard/components/layout/Layout.tsx
  dashboard/components/layout/context/GlobalAppContext.tsx
  dashboard/components/onboarding-wizard/CredentialsButton.tsx
  dashboard/components/onboarding-wizard/DatabasePurplin.tsx
  dashboard/components/onboarding-wizard/InputFileSelect.tsx
  dashboard/components/onboarding-wizard/LabelledInput.tsx
  dashboard/components/onboarding-wizard/OnboardingWizardLayout.tsx
  dashboard/components/onboarding-wizard/PageHeaders.tsx
  dashboard/components/onboarding-wizard/ProgressBar.tsx
  dashboard/components/onboarding-wizard/PurplinCloud.tsx
  dashboard/components/onboarding-wizard/SelectInput.tsx
  dashboard/components/select/Select.tsx
  dashboard/pages/index.tsx
  dashboard/pages/onboarding/choose-cloud.tsx
  dashboard/pages/onboarding/choose-database.tsx
  dashboard/pages/onboarding/complete.tsx
  dashboard/pages/onboarding/database/postgres.tsx
  dashboard/pages/onboarding/database/sqlite.tsx
  dashboard/pages/onboarding/provider/aws.tsx
  dashboard/pages/onboarding/provider/azure.tsx
  dashboard/pages/onboarding/provider/civo.tsx
  dashboard/pages/onboarding/provider/digitalocean.tsx
  dashboard/pages/onboarding/provider/kubernetes.tsx
  dashboard/public/assets/img/database/db-arrow-vector.svg
  dashboard/public/assets/img/database/postgresql.svg
  dashboard/public/assets/img/database/selectdb-komiser.svg
  dashboard/public/assets/img/database/sqlite.svg
  dashboard/public/assets/img/others/arrow-down.svg
  dashboard/public/assets/img/others/empty-dashboard.png
  dashboard/public/assets/img/others/onboarding-cloud.svg
  dashboard/styles/globals.css
  dashboard/utils/providerHelper.ts
Labels: ui
